/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Aug 9, 2011, 3:44:37 PM
 */
package ui;

import ui.grids.Policygrid;
import core.algo.Qlambda;
import core.algo.Qlearning;
import core.algo.SarsaLambda;
import core.algo.basicAlgorithm;
import core.gridMatrix;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.settings.lambdaSettings;
import ui.settings.qlearningSettings;

/**
 *
 * @author robocup
 */
public class MainPanel extends javax.swing.JPanel {

    gridMatrix matrix;
    int N = 7;
    JFrame settingsFrame = new JFrame();
    boolean convergence = false;

    /** Creates new form MainFrame */
    public MainPanel() {
        initComponents();
        matrix = new gridMatrix(N, N);
        matrix.initMatrix();
        jComboBox1.addItem(new Qlambda(matrix));
        jComboBox1.addItem(new SarsaLambda(matrix));
        jComboBox1.addItem(new Qlearning(matrix));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Reinforcement learning"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select algorithm"));

        jLabel1.setText("Select algorithm:");

        jButton1.setText("Adjust algorithm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit world");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 129, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Start"));

        jButton3.setText("Run episode per episode");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Run all episodes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Walk");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*
        JFrame f = new JFrame("Edit World");
        
            
        JPanel pan = new JPanel();
        pan.setLayout(new BoxLayout(pan, BoxLayout.Y_AXIS));

        Editablegrid g = new Editablegrid(matrix);
        pan.add(g);

        wind w = new wind(matrix.getWind());
        pan.add(w);

        f.setContentPane(pan);
        f.setSize(pan.getPreferredSize());
        //f.setResizable(false);
        f.setVisible(true);
         */
        editableWorldFrame f = new editableWorldFrame(matrix);
//NewJDialog f = new NewJDialog(matrix, null, false);
//f.setVisible(true);

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        basicAlgorithm algo = (basicAlgorithm) jComboBox1.getSelectedItem();
        jComboBox1.setEnabled(false);
        algo.runAll();
        convergence = true;
        JOptionPane.showMessageDialog(null, "Convergence achieved after " + algo.getIterationCount() + " iterations!" , "Status message", JOptionPane.INFORMATION_MESSAGE);
        /*
        JFrame f = new JFrame("View Policy");
        Policygrid g = new Policygrid(matrix);
        f.setContentPane(g);
        f.setSize(g.getPreferredSize());
        //f.setResizable(false);
        f.setVisible(true);
         */
        jButton4.setEnabled(!convergence);
        jButton3.setEnabled(!convergence);
        jButton6.setEnabled(!convergence);
        policyWorldFrame f = new policyWorldFrame(matrix, algo.getIterationCount());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!settingsFrame.isVisible()) {
            basicAlgorithm selected = (basicAlgorithm) jComboBox1.getSelectedItem();
            if (selected instanceof Qlearning) {
                settingsFrame = new qlearningSettings(selected);
            }
            if (selected instanceof Qlambda || selected instanceof SarsaLambda) {
                settingsFrame = new lambdaSettings(selected);
            }

            
            settingsFrame.setVisible(true);
            settingsFrame.setResizable(false);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        basicAlgorithm algo = (basicAlgorithm) jComboBox1.getSelectedItem();
        if (!convergence) {
            jComboBox1.setEnabled(false);
            jButton4.setEnabled(!convergence);
            jButton3.setEnabled(!convergence);
            jButton6.setEnabled(!convergence);
            convergence = algo.runOnce();
            /*
            JFrame f = new JFrame("View Policy");
            Policygrid g = new Policygrid(matrix);
            f.setContentPane(g);
            f.setSize(g.getPreferredSize());
            //f.setResizable(false);
            f.setVisible(true);
             */

            policyWorldFrame f = new policyWorldFrame(matrix, algo.getIterationCount());
        } else {
            JOptionPane.showMessageDialog(null, "Convergence achieved after " + algo.getIterationCount() + " iterations!" , "Status message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //matrix = new gridMatrix(N, N);
        //matrix.initMatrix();
        matrix.resetMatrix();
        convergence=false;
        jButton4.setEnabled(!convergence);
        jButton3.setEnabled(!convergence);
        jButton6.setEnabled(!convergence);
        jComboBox1.removeAllItems();
        jComboBox1.setEnabled(true);
        jComboBox1.addItem(new Qlambda(matrix));
        jComboBox1.addItem(new SarsaLambda(matrix));
        jComboBox1.addItem(new Qlearning(matrix));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        basicAlgorithm algo = (basicAlgorithm) jComboBox1.getSelectedItem();
        walkableWorldFrame f = new walkableWorldFrame(matrix, algo);
    }//GEN-LAST:event_jButton6ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame f = new JFrame();
                MainPanel m = new MainPanel();
                f.setContentPane(m);
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setSize(m.getPreferredSize());
                f.setVisible(true);
            }
        });
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
